### ISSUE TITLE
Provide reconnect feature with save sessionId

### ISSUE THREAD

**Issue by daimonkor** [doorbash/agar.io-clone#1]
Hi, please help
I can not impelment feature with save session_id

My state - user disconnected from server and until try reconnect along 20 seconds, I want use the same session_Id and the same room (roomId and name).

I found the same feature you resolved at client, but I found you triyed to reconnect as new user (no as disconnected). 

https://discuss.colyseus.io/topic/221/java-colyseus-client-problem-with-reconnect

Thanks for help

**Comment by doorbash** [comment]
Hi @daimonkor please check if new release of colyseus-java `v1.2.3` has resolved your issue or not thanks

**Comment by daimonkor** [comment]
Hi, @doorbash , No, my task for colyseus-java was about only rejoin function, join function work normal. Server does not work normal with my request (join/rejoin). Problem is with calculation hasReachMaxClient and using options object. When I use 2 maxClients - got crush, use 3 - work, but it is no good, I have turn based server for 2 players room. Thanks for help.

**Comment by daimonkor** [comment]
@doorbash I think about current task, you don`t save sessionId http://prntscr.com/mw9w7x and server remove user http://prntscr.com/mw9x2x. Every connect to server as new user, I think reconnect is more valid (when lost Internet connection). Magic is use reconnect to server at client onLeave callback only when internet connection is lost or other lost connection logic. Mda RxJava, RxJava)). It is more powerfull tool for callbacks and states.

**Comment by doorbash** [comment]
I think you're right. Actually currently i have not enough time to work on this project. Do you mind submitting a pull request for the changes you're asking? I will accept it after a quick review. thanks.

**Comment by daimonkor** [comment]
@doorbash I will try implement decision, maybe it will success
